Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/LineLength:
  Max: 100