name: PatrickF1/GraceTunes/PatrickF1/GraceTunes
on:
  push:
    branches:
    - main
env:
  FEEDBACK_URL: xxxxlink
  GOOGLE_CLIENT_ID: xxxx.com
  GOOGLE_CLIENT_SECRET: xxxxxnx6
  REQUEST_SONG_URL: xxxxlink
  SECRET_KEY_BASE: xxxx9e7e
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/ruby:3.3.0-node
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PORT: 3000
        WEB_CONCURRENCY: 1
        RAILS_ENV: test
    services:
      postgres:
        image: cimg/postgres:15.6
        env:
          POSTGRES_USER: gracetunes_user
          POSTGRES_DB: tunes_test
          POSTGRES_PASSWORD: ''
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Which bundler?
      run: bundle -v
    - name: restore_cache
      uses: actions/cache@v3.3.2
      with:
        key: gracetunes-bundle-v2-{{ checksum "Gemfile.lock" }}
        path: vendor/bundle
        restore-keys: |-
          gracetunes-bundle-v2-{{ checksum "Gemfile.lock" }}
          gracetunes-bundle-v2-
    - name: Bundle Install
      run: bundle check || bundle install
    - name: Rubocop autocorrections check
      run: bundle exec rubocop --fail-level W
    - name: Wait for DB
      run: dockerize -wait tcp://localhost:5432 -timeout 1m
    - name: Database setup
      run: bundle exec rails db:schema:load --trace
    - name: Run minitest in parallel
      run: bundle exec rails test
    - uses: actions/upload-artifact@v4.0.0
      with:
        path: test/reports
